로그인페이지 전체 레이아웃 수정
WebVolume/volume-client pull request #12
Opened 2022-02-15 11:07 UTC by Yeom-JinHo

너무 반응형 생각안하고 만든거 같아서 수정하였습니다.

2022-02-15 11:08 UTC, Yeom-JinHo commented
일단 fs-* 많이 사용하여서 수정하였는데 이렇게 되면 일단 너무 classNam부분이 길어지는 부분이 있는데

2022-02-15 11:09 UTC, Yeom-JinHo commented
일단 fs-* 많이 사용하여서 수정하였는데 이렇게 되면 일단 너무 classNam부분이 길어지는 부분이 있는데
통일하는 편이 좋을까요? 혹시 현업에서는 어떤식으로 진행하는지 궁금합니다. ( flex, align만 보통 빼나요? )

2022-02-15 11:09 UTC, Yeom-JinHo commented
그리고 계속해서 fs-* 사용한다면 vw,vh같이 적용하면 좋을꺼 같습니다!

2022-02-15 11:12 UTC, Yeom-JinHo commented
#8 동일한 이슈 font,color에 생겨서 
reset 부분에서 font와 color 상속으로 바꿔두었는데 이런경우 혹시 차후에 문제가 생길 수 있을까요?
 저는 계속해서 부모에서 덮어주면 된다고 생각해서 바꾸긴 했습니다만! 혹시나 해서요

2022-02-15 11:15 UTC, Yeom-JinHo commented
일단 리뷰요청은 넣어두니, 시간되실때 확인해주세요!! 급한게 아니라서

2022-02-16 00:24 UTC, minsoo-web commented
> 일단 fs-* 많이 사용하여서 수정하였는데 이렇게 되면 일단 너무 classNam부분이 길어지는 부분이 있는데 통일하는 편이 좋을까요? 혹시 현업에서는 어떤식으로 진행하는지 궁금합니다. ( flex, align만 보통 빼나요? )

보통 타이포그래피가 이렇게 많이 나오지 않습니다. 
예를 들어서
타이틀, 서브타이틀, 본문, description 등등 많아야 5 ~ 6개 정도의 폰트 사이즈를 가지고 통일성있게 사용하는데
이건 디자인 작업이 폰트 사이즈가 너무 다양하게 사용된거라 어쩔 수 없습니다. 

저는 그리고 회사에서는 styled-components 를 사용하기 때문에 현업에서 scss로 className을 어떻게 활용하는지 잘 모릅니다...

2022-02-16 00:25 UTC, minsoo-web commented
>

2022-02-16 00:26 UTC, minsoo-web commented
> 그리고 계속해서 fs-* 사용한다면 vw,vh같이 적용하면 좋을꺼 같습니다!

vh를 폰트사이즈에 왜 적용하나요?
브라우저 세로 크기에 따라서 폰트 크기가 달라져야 하는 게 아닐텐데..

2022-02-16 00:27 UTC, minsoo-web commented
> #8 동일한 이슈 font,color에 생겨서 reset 부분에서 font와 color 상속으로 바꿔두었는데 이런경우 혹시 차후에 문제가 생길 수 있을까요? 저는 계속해서 부모에서 덮어주면 된다고 생각해서 바꾸긴 했습니다만! 혹시나 해서요

혹시 질문이 이해가 잘 안되는데 다시 한 번만 설명해주실 수 있나요..?

2022-02-16 00:40 UTC, minsoo-web requested changes
회원가입을 눌렀을 때 소셜 로그인 모달이 뜹니다. 

소셜 로그인 모달은 카카오 로그인, 구글 로그인을 눌렀을 때 가입되어있지 않는 유저의 경우 뜨는 모달창이기 때문에 플로우가 수정되어야 할 것 같습니다.

as is
sign up -> 소셜 회원가입 모달

to be 
sign up -> 이메일 회원가입 모달

2022-02-16 15:42 UTC, Yeom-JinHo commented
아 타이포그래피에서 fs-*의 중복이 너무 많이 발생하는거 같아서 중복을 줄여보고자 말씀드린거였습니다!
생각해보니 className으로 빼서 안되겠군요

2022-02-16 15:45 UTC, Yeom-JinHo commented
#8  이슈처럼 font,color가 상속받지 못하여서 reset.css 에서 font와 color 부분 상속으로 설정해두었는데,

차후에 상속때문에 구조가 복잡해지거나 스타일이 깨지거나 그런게 혹~시나 발생할 수 있는지 여쭤본거였습니다!

2022-02-16 15:47 UTC, Yeom-JinHo commented
모달부분 레이아웃작업하느라 띄워뒀는데 수정안되었나보네요 수정하겠습니다 -- !

2022-02-17 12:36 UTC, Yeom-JinHo commented
로그인페이지(홈)부분 반응형 작업했습니다--!
모바일뷰에서 햄버거 버튼 아직 레이아웃이 완료안되어서 레이아웃 전달받는대로 바로 추가 작업하도록 하겠습니다:)

2022-02-19 05:38 UTC, Yeom-JinHo commented
모바일 햄버거버튼누르면 사이드탭 나오는 부분까지 작업완료하였습니다!
작업하다보니 desktop, tablet ,phone 이렇게 작업하였는데 아무래도 Phone보다는 mobile이 네이밍이 더 어울리려나요?

2022-02-19 07:46 UTC, minsoo-web requested changes
약간 수정하셔야 할 사항도 있고 확인하셔야 할 사항들이 조금 있는데 확인 후 수정해주시면 알려주세요!

2022-02-19 07:46 UTC, minsoo-web commented on src/components/SignModal/Modal.scss
> +@media screen and (max-width: 764px) {
이건 당장 바꾸실 필요는 없는데 max-width: 764 도 변수로 처리하는게 좋습니다. 
밑에 모바일 버전도 마찬가지구요!
기준점이 같이 움직이니까 만약에 디자인이 수정되어야 하는 경우가 생겼을 때 일일이 파일 전체를 다 뒤져가며 수정하지 않아도 되는 장점이 있습니다

2022-02-19 07:46 UTC, minsoo-web commented on src/components/SignModal/SignInModal/SignInModal.scss
> +      margin: 0vw vw(5px);
0에는 단위 안 붙이셔도 됩니다!

2022-02-19 07:46 UTC, minsoo-web commented on src/components/SignModal/SignInModal/SignInModal.scss
> +        border: vw(1px) solid $GRAY_C2;
border 는 반응형으로 작업 안 하는 편입니다. 
1px solid $GRAY_C2; 로 변경하는 게 좋겠네요!

2022-02-19 07:46 UTC, minsoo-web commented on src/components/SignModal/SignInModal/SignInModal.scss
> +        margin: 0vw vw-t(5px);
0에는 단위 안 붙이셔도 됩니다!

2022-02-19 07:46 UTC, minsoo-web commented on src/components/SignModal/SignInModal/SignInModal.scss
> +          border: vw-t(1px) solid $GRAY_C2;
border는 반응형으로 안 하셔도 됩니다!

2022-02-19 07:46 UTC, minsoo-web commented on src/components/SignModal/SignInModal/SignInModal.scss
> +          font-size: vw-p(12px);
폰트 사이즈는 fs-12 가 있지 않나요?
typography 에서 미디어쿼리 처리를 해주었기 때문에 클래스로 처리하면 이런 작업을 안 하셔도 됩니다

2022-02-19 07:46 UTC, minsoo-web commented on src/components/SignModal/SignInModal/SignInModal.scss
> +          margin-bottom: vw-p(6px);
이건 그냥 진짜 흘려들으셔도 되는데 css도 순서를 중요하게 생각하는 사람들이 있더라구요

박스요소
색상
폰트

이순서였나? 암튼 이런 식으로 css 적는 것도 순서를 정하는 컨벤션을 두자 뭐 이런게 있는데 
이거를 제가 하자는 얘기는 아니고 진호님도 나름대로의 규칙을 두고 같은 순서대로 작성하시는 습관을 들이면 좋습니다. 
저도 항상 지키는 건 아니지만 박스요소 > 색상 > 폰트 이 순서를 지키려고 노력합니다. 

예를 들어서

```css
.foo {
  font-size: 12px;
  display: flex;
  background-color: black;
  justify-content: center;
  font-weight: bold;
}
```
이렇게 하는 게 다른 사람이 보기에도 본인이 나중에 수정작업을 할 때도 편할겁니다.
```css
.good {
  display: flex;
  justify-content: center;

  background-color: black;

  font-size: 12px;
  font-weight: bold;
}
```

> 여백 두는 건 그냥 제 습관입니다.

2022-02-19 08:15 UTC, Yeom-JinHo commented on src/components/SignModal/Modal.scss
> +@media screen and (max-width: 764px) {
넵!

2022-02-19 08:15 UTC, Yeom-JinHo commented on src/components/SignModal/SignInModal/SignInModal.scss
> +        border: vw(1px) solid $GRAY_C2;
넵 변경하겠습니다!

2022-02-19 08:16 UTC, Yeom-JinHo commented on src/components/SignModal/SignInModal/SignInModal.scss
> +          margin-bottom: vw-p(6px);
넵 차후 작업할때 최대한 고려해서 작업해보겠습니다 :)
항상 피드백 잘 주셔서 너무 감사합니다

2022-02-19 09:02 UTC, minsoo-web approved these changes
고생하셨습니다! 머지 후 배포하겠습니다

2022-02-19 09:02 UTC, minsoo-web commented on src/components/SignModal/SignInModal/SignInModal.scss
>          text-align: start;
text-align: start는 디폴트인데 따로 두신 이유가 있으신가요?

2022-02-19 09:02 UTC, merged