[퍼블리싱] 디테일 페이지
WebVolume/volume-client pull request #18
Opened 2022-03-09 15:46 UTC by Yeom-JinHo

디테일 페이지 퍼블리싱입니다.

Profile부분 PR 닫아주시면 반응형까지 작업해서 말씀드리겠습니다 :)

<img width="1429" alt="스크린샷 2022-03-10 오전 12 44 00" src="https://user-images.githubusercontent.com/81306489/157476764-a87d42b3-81c5-4db6-a88e-da99e1b60244.png">
<img width="1334" alt="스크린샷 2022-03-10 오전 12 44 07" src="https://user-images.githubusercontent.com/81306489/157476737-a50aa151-dd0e-4f92-b3e7-358e165d6d67.png">

2022-03-19 10:28 UTC, minsoo-web commented
<img width="367" alt="스크린샷 2022-03-19 오후 7 26 57" src="https://user-images.githubusercontent.com/57122180/159117378-d812f602-83dd-4397-a99a-237647c40041.png">

모바일 뷰에서 width 조정이 필요해보입니다!

2022-03-19 10:33 UTC, minsoo-web commented
1. 카테고리 최대 개수가 정해져있는지 희윤님한테 한 번 여쭤봐주세요, 만약 제한이 없는 경우 줄바꿈 처리로 바꿔야 할 것 같습니다.
<img width="376" alt="스크린샷 2022-03-19 오후 7 28 58" src="https://user-images.githubusercontent.com/57122180/159117428-a19447f0-a32e-4dd3-8d12-49aff11028d3.png">
<img width="859" alt="스크린샷 2022-03-19 오후 7 29 26" src="https://user-images.githubusercontent.com/57122180/159117442-bf687f52-dad4-4465-974d-6d24c4f64a90.png">

3. width로 처리하는 것이 아니라 padding으로 처리해야 할 것으로 보입니다. 폰트 사이즈의 최소 크기는 10px이기 때문에 크기가 반응형으로 줄어도 여백이 유지되지 않습니다. 
<img width="1155" alt="스크린샷 2022-03-19 오후 7 30 56" src="https://user-images.githubusercontent.com/57122180/159117478-1a073d50-abe2-4918-b153-ca4da4026772.png">

2022-03-19 10:45 UTC, minsoo-web commented
이건 사실 이전 PR때 확인했어야 하는 부분인데 제가 미처 확인하지 못했네요

<img width="561" alt="스크린샷 2022-03-19 오후 7 39 25" src="https://user-images.githubusercontent.com/57122180/159117716-dde0e5bc-09f7-409f-9d50-893158a91882.png">

<img width="162" alt="스크린샷 2022-03-19 오후 7 39 48" src="https://user-images.githubusercontent.com/57122180/159117728-b4f98cae-24fa-40b0-9a17-24e029a95a8b.png">

가운데 정렬이 안 되어있는 것 같습니다. 
모바일 크기로 보면 더 심해서 발견했습니다 ㅠ

2022-03-19 12:37 UTC, minsoo-web requested changes
리뷰 모두 남겼습니다~! 고생하셨어요! 수정 완료되면 노티 부탁드립니다.

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicCommentList/MusicCommentList.tsx
> +      <input type="text" className="music-comment-list__input fs-16 fc-white" />
희윤님에게 확인받아야 하는 부분 같아 보입니다. 멀티라인으로 늘어나야 하는 부분이라면 textarea 로 처리해야 할 것으로 보입니다. 
만약 멀티라인이라면 최대 라인(max-height) 을 확인해서 처리해야 할 것으로 보입니다.

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Common/CircleList/CircleList.tsx
> +  console.log(title);
불필요한 console.log 삭제 부탁드립니다!

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Common/CircleList/CircleList.tsx
> +import { PlayList as testColor } from "@constants/Colors";
as 를 쓰신 이유가 따로 있으실까요?

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Common/CircleList/CircleList.scss
> +  margin: vw(28px) 0 vw(59px) vw(28px);
1. 마진 병합 이슈가 있습니다. 
2. "이 곡이 있는 플레이리스트"와 사이 간격은 28px이 아니라 38입니다.

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Common/CircleList/CircleList.tsx
> +          ></li>
클릭 가능한 요소인지 확인해봐야 할 것 같습니다. 
또한 원래는 색상이 아니라 유저 프로필 사진이 들어가는 게 아닌지 확인해봐야 할 것으로 보입니다.

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicCommentList/MusicComment/MusicComment.tsx
> +      <img src={testImg} alt="" className="music-comment__img" />
클릭 가능한 요소인지 확인해봐야 할 것으로 보입니다. alt 채워주시길 바랍니다.

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicCommentList/MusicComment/MusicComment.tsx
> +        <p className="music-comment-main__id fs-14">{id}</p>
댓글 작성에 길이 제한이 없는지, 특정 길이 이상일 경우 더보기로 처리하지는 않는지 확인해봐야 할 것 같습니다

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicCommentList/MusicComment/MusicComment.tsx
> +        <p className="music-comment-main__id fs-14">{id}</p>
아 이 부분은 유저네임이네요.. music-comment-main__content 요소의 코멘트라고 봐주세요!

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicInfoIconList/MusicInfoIconList.tsx
> +          </li>
클릭 가능한 요소로 보이며 alt는 이미지가 안 보일 때 액박으로 처리되어야 하는 부분으로 다르게 표현해야 할 것으로 보입니다. 
a 태그로 감싸고 title 요소를 넣어 hover 의 경우를 고려해서 작업해주세요

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicInfoIconList/MusicInfoIconList.tsx
> +            <p>50</p>
k 로 세는 것이 좋아보이는데 희윤님과 상의해보심이 어떨까 싶습니다. 
모두 세자리 수 이상일 때 999+ 로 하면 레이아웃이 깨집니다

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicSpinner/MusicSpinner.tsx
> +        />
클릭 가능한 요소로 보이며 
1. alt 자세하게 변경,
2. a 태그 title 처리 부탁드립니다.

2022-03-19 12:37 UTC, minsoo-web commented on src/navigation/RootRouter.tsx
> +        <Route path="detail/*" element={<Detail />}></Route>
라우트 설계를 지금 코멘트 남길 필요는 없어 보이긴하지만,

detail/<music_id> 이런식으로 설계하는 것이 좋아보입니다. 
url 만으로 해당 페이지에 접근할 수 있도록요

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicDescription/MusicDescription.tsx
> +            {catogory}
이거 클릭가능한 요소인지 확인 한 번만 부탁드려요
클릭하면 해당 카테고리로 음악 검색이 들어간다던지,,

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +            </div>
이 부분 화면 조금만 줄여도 1... 으로 보이는데 k로 세고 반응형 이슈 때문에 레이아웃 개선이 필요해보인다고 희윤님한테 한 번 말씀해주세요

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +          팔로우 취소
클릭 가능한 요소로 처리 부탁드립니다.

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +      />
클릭 가능한 요소로 보이는데 확인 부탁드립니다.

2022-03-19 12:37 UTC, minsoo-web commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +              alt=""
alt 채워주시길 바랍니다

2022-03-27 03:25 UTC, Yeom-JinHo commented on src/components/Common/CircleList/CircleList.tsx
> +  console.log(title);
수정완료.

2022-03-27 03:26 UTC, Yeom-JinHo commented on src/components/Common/CircleList/CircleList.tsx
> +import { PlayList as testColor } from "@constants/Colors";
따로 이유없고 현재 테스트컬러가 따로 없어서 있길래 사용하였습니다. 그래서 testColor라고 네이밍 하였습니다!

2022-04-02 07:48 UTC, Yeom-JinHo commented
희윤님께 음악 카테고리 부분 최대 개수 3개로 전달 받아서 따로 레이아웃은 처리해야할 부분 없을꺼 같고,
클릭 가능요소로 변경하겠습니다.

2022-04-02 07:57 UTC, Yeom-JinHo commented
999 오버시 K,M 사용하도록 3자리까지 디자인 수정하였다고 하셨습니다

2022-04-02 08:03 UTC, Yeom-JinHo commented
999 오버시 K,M 변환 작업은 따로 빼야할꺼 같은데 어디에 빼는게 좋을까요?

2022-04-02 08:05 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +            </div>
확인완료

2022-04-02 08:07 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +          팔로우 취소
클릭가능요소로 변환완료

2022-04-02 08:07 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +      />
클릭시 --> 유저페이지로 이동으로 확인하였습니다.

2022-04-02 08:09 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +              alt=""
완료

2022-04-02 08:39 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/MusicCommentList/MusicCommentList.tsx
> +      <input type="text" className="music-comment-list__input fs-16 fc-white" />
textarea로 변경완료

2022-04-02 09:57 UTC, Yeom-JinHo commented on src/components/Common/CircleList/CircleList.scss
> +  margin: vw(28px) 0 vw(59px) vw(28px);
확인 후 수정하였씁니다

2022-04-02 10:06 UTC, Yeom-JinHo commented on src/components/Common/CircleList/CircleList.tsx
> +          ></li>
클릭요소로 확인하였고 유저 프로필로 대치하도록 하겠습니다~!

2022-04-02 10:21 UTC, Yeom-JinHo commented on src/components/Detail/MusicInfoIconList/MusicInfoIconList.tsx
> +            <p>50</p>
K,M으로 작업하는게 좋다고 하셨어요.
K,M 으로 변경하는 부분 어디로 빼면 좋으려나요?

2022-04-02 10:25 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/MusicCommentList/MusicComment/MusicComment.tsx
> +      <img src={testImg} alt="" className="music-comment__img" />
클릭 가능요소로 변경, alt도 채웠습니다-!

2022-04-02 10:37 UTC, Yeom-JinHo commented on src/navigation/RootRouter.tsx
> +        <Route path="detail/*" element={<Detail />}></Route>
차후 백단 붙일때 참고하여 설계하겠습니다 :)

2022-04-02 10:50 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/MusicCommentList/MusicComment/MusicComment.tsx
> +        <p className="music-comment-main__id fs-14">{id}</p>
길이 제한은 따로 두시지 않는다고 하셔서 그대로 작업하겠습니다.

2022-04-02 10:50 UTC, Yeom-JinHo commented on src/components/Detail/MusicInfoIconList/MusicInfoIconList.tsx
> +          </li>
button으로 작업완료하였습니다!

2022-04-02 10:57 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/MusicDescription/MusicDescription.tsx
> +            {catogory}
클릭 가능 요소로 변경완료

2022-04-03 03:55 UTC, minsoo-web commented
> 999 오버시 K,M 변환 작업은 따로 빼야할꺼 같은데 어디에 빼는게 좋을까요?

utils 폴더하나 만들구 getCounts 같은 함수 하나 만들어서 카운트 개수에 따라서 다르게 보여지게끔 처리하면 될 것 같습니다

2022-04-03 04:41 UTC, minsoo-web requested changes
몇 가지 리뷰 사항이 있습니다! 반영해서 작업해주세요

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicCommentList/MusicComment/MusicComment.tsx
> +const MusicComment = ({ id, content, date, reply }: any) => {
나중에 api를 통해 데이터 받게하면 타입 지정해주시는 방향으로 수정해주세요!

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Common/CircleList/CircleList.tsx
> +import { PlayList as testColor } from "@constants/Colors";
안 쓰이는 import 는 삭제해주세요

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Common/CircleList/CircleList.tsx
> +import React from "react";
react 16 버전 이후로는 import 를 안 해도 됩니다. 안 쓰이는 import 로 삭제해도 될 것 같습니다. 
vscode에는 안 쓰이는 import 정리하는 단축키가 있습니다.
mac 기준: `shift + option + o`
진호님 맥쓰시는 걸로 기억하는데 윈도우여도 찾아보시면 될 겁니다! 유용한 단축키이니 외워두시면 좋을 것 같습니다.

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Common/CircleList/CircleList.tsx
> +          <a href={dummy.id + "번"} title="해당유저로 이동">
특정 라우트로 이동하는 기능이므로 a태그가 아닌, Link 태그로 처리하는 것이 맞는 것 같습니다.

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Common/CircleList/CircleList.tsx
> +          <a href={dummy.id + "번"} title="해당유저로 이동">
https://stackoverflow.com/questions/43087007/react-link-vs-a-tag-and-arrow-function

a 태그와 react-router-dom 의 Link 태그의 차이점은 레퍼런스 참조를 해보시면 확인 할 수 있습니다.

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicCommentList/MusicComment/MusicComment.tsx
> +      <a href="" title="해당 유저로 이동">
라우트가 변경되는 거니까 Link 태그를 쓰는 게 좋아보입니다. 
title도 props로 받은 유저의 정보를 받아서 "<유저이름>유저 페이지로 이동" 으로 동적으로 변환 시키는 게 더 좋아보입니다. 

> 해당 데이터는 아직 없으니, 나중에 api 연동 작업을 하시면 작업하셔도 좋을 것 같습니다.

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicCommentList/MusicCommentList.tsx
> +    let textarea = document.getElementById("autoTextarea");
react에서 요소를 직접 조작, 참조할 때는 ref를 쓰시는 게 좋습니다. 

https://simsimjae.tistory.com/417
https://stackoverflow.com/questions/37273876/reactjs-this-refs-vs-document-getelementbyid

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicCommentList/MusicCommentList.tsx
> +        onKeyUp={autoResizeTextarea}
onKeyPress 하나로 합칠 수 있을 것 같습니다.

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicCommentList/MusicCommentList.tsx
> +        onKeyUp={autoResizeTextarea}
state로 댓글 데이터를 받아야 하는 부분 같습니다. 
렌더링 최적화를 위해서 state 변화가 있는 textArea 부분만 컴포넌트 분리를 하는 것이 좋아보입니다. 

진호님 코드에서 state만 추가한 상태

https://user-images.githubusercontent.com/57122180/161411590-80935381-2978-4836-a2c7-0f90a8250de9.mov

컴포넌트 분리한 상태

https://user-images.githubusercontent.com/57122180/161411625-147a409c-1a3a-4fb2-8135-8ed23797d1d8.mov

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicCommentList/MusicCommentList.tsx
> +        onKeyUp={autoResizeTextarea}
추가로 resize none 스타일코드도 넣어주세요

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Detail/MusicAbout/MusicDescription/MusicDescription.tsx
> +            href=""
검색 라우트로 이동하는 것으로 이 부분도 Link 태그로 변경하는 것이 좋아보입니다. 
일단은 냅두고 나중에 검색 페이지 설계가 끝나고 난 뒤에 진행해도 괜찮을 것 같습니다.

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +import testImg from "../../../../assets/images/background.png";
`@images` path alias 활용해주세요~!

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +      <a href="" title="유저페이지로 이동">
Link 컴포넌트로 활용해주세요

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Detail/MusicInfoIconList/MusicInfoIconList.tsx
> +  };
musicLike에 종속성이 걸린 함수입니다. 
useCallback을 활용해 렌더링 최적화 작업을 해주세요

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Detail/MusicInfoIconList/MusicInfoIconList.tsx
> +              src={musicLike ? fullHeartIcon : emptyHeartIcon}
useMemo를 통해 따로 선언해주세요.
```ts
const HeartIcon = useMemo(()=> musicLike ? fullHeartIcon : emptyHeartIcon ,[musicLike]);
```

2022-04-03 04:41 UTC, minsoo-web commented on src/components/Common/MiniTrack/MiniTrack.tsx
> +      <button className="mini-track__play-btn flex align-center justify-center">
title 추가해주세요~!

2022-04-03 07:12 UTC, Yeom-JinHo commented on src/components/Common/CircleList/CircleList.tsx
> +import { PlayList as testColor } from "@constants/Colors";
넵

2022-04-03 07:17 UTC, Yeom-JinHo commented on src/components/Common/CircleList/CircleList.tsx
> +import React from "react";
넵!! 일단 디테일 부분만 import 안쓰는거 정리하고 차후에 다른 브랜치에서 나머지 지우겠습니다--!

2022-04-03 07:20 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/MusicCommentList/MusicComment/MusicComment.tsx
> +      <a href="" title="해당 유저로 이동">
넵! 연동작업하면서 추가로 작업하겠습니다

2022-04-03 07:22 UTC, Yeom-JinHo commented on src/components/Common/CircleList/CircleList.tsx
> +          <a href={dummy.id + "번"} title="해당유저로 이동">
레퍼런스까지 감사합니다 :)

2022-04-03 07:50 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/MusicCommentList/MusicCommentList.tsx
> +    let textarea = document.getElementById("autoTextarea");
넵!

2022-04-03 07:55 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/MusicCommentList/MusicCommentList.tsx
> +        onKeyUp={autoResizeTextarea}
넵 수정하였습니다-!

2022-04-03 07:56 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +import testImg from "../../../../assets/images/background.png";
넵!

2022-04-03 07:57 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/MusicDescription/MusicDescription.tsx
> +            href=""
일단 수정하였습니다--!

2022-04-03 07:58 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/UserAbout/UserAbout.tsx
> +      <a href="" title="유저페이지로 이동">
넹

2022-04-03 07:59 UTC, Yeom-JinHo commented on src/components/Detail/MusicInfoIconList/MusicInfoIconList.tsx
> +  };
넵 변경하였습니다

2022-04-03 08:00 UTC, Yeom-JinHo commented on src/components/Common/MiniTrack/MiniTrack.tsx
> +      <button className="mini-track__play-btn flex align-center justify-center">
넵

2022-04-03 08:01 UTC, Yeom-JinHo commented on src/components/Detail/MusicInfoIconList/MusicInfoIconList.tsx
> +              src={musicLike ? fullHeartIcon : emptyHeartIcon}
넵

2022-04-03 08:03 UTC, Yeom-JinHo commented on src/components/Detail/MusicAbout/MusicCommentList/MusicComment/MusicComment.tsx
> +const MusicComment = ({ id, content, date, reply }: any) => {
차후에 데이터 받아올때 수정하겠습니다--!

2026-03-17 13:54 UTC, closed without merging