프로필 페이지 퍼블리싱
WebVolume/volume-client pull request #5
Opened 2022-02-03 11:44 UTC by Yeom-JinHo

<img width="3360" alt="스크린샷 2022-02-03 오후 8 23 22" src="https://user-images.githubusercontent.com/81306489/152336106-5ee7d914-60f4-46d0-bbf7-f097ebeb523b.png">
<img width="3360" alt="스크린샷 2022-02-03 오후 8 23 30" src="https://user-images.githubusercontent.com/81306489/152336216-84ff4b13-ae2e-453e-bee1-1bd34bebfe45.png">

Main에 Upload file 부분 희윤님이 작업해주시는대로 작업해서 올리겠습니다.

2022-02-12 06:25 UTC, minsoo-web requested changes
몇 가지 수정사항 남겼습니다. 확인 후 수정 작업 요청드립니다.

2022-02-13 04:02 UTC, minsoo-web requested changes
수정사항 조오금 남았습니다 그 부분만 처리해주세요..!

2022-02-13 04:02 UTC, minsoo-web commented on src/components/Common/InlinePlayLists/InlinePlayLIst/TrackBarList/TrackBarList.tsx
> +            <TrackBar />
TrackBar 최상단 부모가 li 아닌가요?

2022-02-13 04:02 UTC, minsoo-web commented on src/components/Common/InlinePlayLists/InlinePlayLIst/TrackBarList/TrackBarList.tsx
> +            <TrackBar />
map 구문은 간단하게 {}과 return 을 없애고 단축형으로 사용해주세요!

2022-02-13 04:02 UTC, minsoo-web commented on src/components/Profile/ProfileMain/ProfileNav/ProfileNav.tsx
> +              (isActive ? " btn--active" : "btn--unactive")
반복되는 값이라 useMemo로 compute 시켜서 재사용하는 게 좋을 것 같아요

2022-02-13 04:02 UTC, minsoo-web commented on src/components/Profile/UserStats/UserStats.tsx
> +        </li>
이거 클릭해도 화면 없는 거 맞죠?
그니까 클릭 가능한 요소가 아니죠?

2022-02-13 04:07 UTC, Yeom-JinHo commented on src/components/Profile/UserStats/UserStats.tsx
> +        </li>
네 맞습니다-!

2022-02-13 09:06 UTC, minsoo-web approved these changes
고생 많으셨습니다! 머지하겠습니다

2022-02-13 09:06 UTC, merged